about/urls.py
from django.urls import path
from . import views

app_name = 'about'
urlpatterns = [
    path('', views.about,name='about'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home,name='home'),
]

login2/urls.py
from django.urls import path
from . import views


app_name = 'login2'
urlpatterns = [
    path('', views.login2,name='login2'),
 ]

logout2/urls.py
from django.urls import path
from . import views


app_name = 'logout2'
urlpatterns = [
    path('', views.logout2,name='logout2'),
 ]

myshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('',include('home.urls')),
    path('about/',include('about.urls')),
    path('register/', include('register.urls')),
    path('login/',include('login2.urls')),
    path('dangxuat/', include('logout2.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views

app_name = 'product'
urlpatterns = [
    path('', views.products,name='list'),
    path('detail/<int:id>', views.detail, name='detail'),
]

home/models.py
from django.db import models

# Create your models here.
class HeroModel(models.Model):
    name = models.CharField(max_length=15)
    text = models.TextField()
    img = models.ImageField(null=False,upload_to="hero/")
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    

home/views.py
from django.shortcuts import render
from .models import HeroModel
from about.models import *

# Create your views here.
def home(request):
    hero = []
    hero = HeroModel.objects.all()
    OurTeam = OurteamModel.objects.all()[:4]
    about = AboutModel.objects.first()
    context = {
        'hero': hero,
        'ourTeam': OurTeam,
        'about': about
    }
    return render(request,"home/home.html",context)

home/templates/home/base.html
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Cake Template">
    <meta name="keywords" content="Cake, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Cake | Template</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600;700;800;900&display=swap"
    rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&display=swap"
    rel="stylesheet">
    {% load static %}
    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/barfiller.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    {% comment %} <div id="preloder">
        <div class="loader"></div>
    </div> {% endcomment %}

    <!-- Offcanvas Menu Begin -->
    <div class="offcanvas-menu-overlay"></div>
    <div class="offcanvas-menu-wrapper">
        <div class="offcanvas__cart">
            <div class="offcanvas__cart__links">
                <a href="#" class="search-switch"><img src="{% static 'img/icon/search.png' %}" alt=""></a>
                <a href="#"><img src="{% static 'img/icon/heart.png' %}" alt=""></a>
            </div>
            <div class="offcanvas__cart__item">
                <a href="#"><img src="{% static 'img/icon/cart.png' %}" alt=""> <span>0</span></a>
                <div class="cart__price">Cart: <span>$0.00</span></div>
            </div>
        </div>
        <div class="offcanvas__logo">
            <a href="{% url "home:home" %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
        </div>
        <div id="mobile-menu-wrap"></div>
        <div class="offcanvas__option">
            <ul>
                <li><a href="{% url "register:register" %}">Sign in</a> <span class="arrow_carrot-down"></span></li>
            </ul>
        </div>
    </div>
    <!-- Offcanvas Menu End -->

    <!-- Header Section Begin -->
    <header class="header">
        <div class="header__top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="header__top__inner">
                            <div class="header__top__left">
                                {% if not request.user.is_authenticated %}
                                <ul>
                                    <li><a href="{% url "register:register" %}">Sign in</a></li>
                                    <li><a href="{% url "login2:login2" %}">Sign up</a></li>
                                </ul>                              
                                {% else %}
                                <ul>
                                    <li>{{request.user.first_name}} {{request.user.last_name}} {{request.user.username}}</li>
                                    <li><a href="{% url 'logout2:logout2' %}">Đăng xuất</a></li>
                                </ul>         
                                {% endif %}
                                
                            </div>
                            <div class="header__logo">
                                <a href="{% url "home:home" %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
                            </div>
                            <div class="header__top__right">
                                <div class="header__top__right__links">
                                    <a href="#" class="search-switch"><img src="{% static 'img/icon/search.png' %}" alt=""></a>
                                    <a href="#"><img src="{% static 'img/icon/heart.png' %}" alt=""></a>
                                </div>
                                <div class="header__top__right__cart">
                                    <a href="#"><img src="{% static 'img/icon/cart.png' %}" alt=""> <span>0</span></a>
                                    <div class="cart__price">Cart: <span>$0.00</span></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="canvas__open"><i class="fa fa-bars"></i></div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <nav class="header__menu mobile-menu">
                        <ul>
                            <li {% if request.resolver_match.url_name == 'home' %}class="active"{% endif %} ><a href="{% url "home:home" %}">Home</a></li>
                            <li {% if request.resolver_match.url_name == 'about' %}class="active"{% endif %}><a href="{% url "about:about" %}">About</a></li>
                            <li {% if request.resolver_match.url_name == 'list' or request.resolver_match.url_name == 'detail'%}class="active"{% endif %}><a href="{% url "product:list" %}">Shop</a></li>
                           
                            {% comment %} <li><a href="./contact.html">Contact</a></li> {% endcomment %}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- Header Section End -->

    {% block content %}
    {% endblock content %}

    <!-- Footer Section Begin -->
    <footer class="footer set-bg" data-setbg="{% static 'img/footer-bg.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="footer__widget">
                        <h6>WORKING HOURS</h6>
                        <ul>
                            <li>Monday - Friday: 08:00 am – 08:30 pm</li>
                            <li>Saturday: 10:00 am – 16:30 pm</li>
                            <li>Sunday: 10:00 am – 16:30 pm</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="footer__about">
                        <div class="footer__logo">
                            <a href="#"><img src="{% static 'img/footer-logo.png' %}" alt=""></a>
                        </div>
                        <p>Lorem ipsum dolor amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                        labore dolore magna aliqua.</p>
                        <div class="footer__social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-youtube-play"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="footer__newslatter">
                        <h6>Subscribe</h6>
                        <p>Get latest updates and offers.</p>
                        <form action="#">
                            <input type="text" placeholder="Email">
                            <button type="submit"><i class="fa fa-send-o"></i></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Footer Section End -->

<!-- Search Begin -->
<div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch">+</div>
        <form class="search-model-form">
            <input type="text" id="search-input" placeholder="Search here.....">
        </form>
    </div>
</div>
<!-- Search End -->


<!-- Js Plugins -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/jquery.barfiller.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/jquery.slicknav.js' %}"></script>
<script src="{% static 'js/jquery.nicescroll.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>

<script src="{% static 'js/main.js' %}"></script>


</body>

</html>

home/templates/home/home.html
{% extends "home/base.html" %}
{% block content %}
<section class="hero">    
    <div class="hero__slider owl-carousel">
        {% for item in hero %}
        <div class="hero__item set-bg" data-setbg="{{item.img.url}}">
            <div class="container">
                <div class="row d-flex justify-content-center">
                    <div class="col-lg-8">
                        <div class="hero__text">
                            <h2>{{item.text}}</h2>
                            <a href="#" class="primary-btn">Our cakes</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>    
</section>
<!-- About Section Begin -->
<section class="about spad">
    <div class="container">
        <div class="row">
            <div class="about__text">
                <div class="section-title">
                    <span>About Cake shop</span>
                    <h2>{{about.head}}</h2>
                </div>
                <p  style="margin-bottom: 60px;">{{about.desc}}</p>
            </div>
        </div> 
    </div>
</section>
<!-- About Section End -->
<!-- Categories Section Begin -->
{% comment %} <div class="categories">
    <div class="container">
        <div class="row">
            <div class="categories__slider owl-carousel">
                <div class="categories__item">
                    <div class="categories__item__icon">
                        <span class="flaticon-029-cupcake-3"></span>
                        <h5>Cupcake</h5>
                    </div>
                </div>
                <div class="categories__item">
                    <div class="categories__item__icon">
                        <span class="flaticon-034-chocolate-roll"></span>
                        <h5>Butter</h5>
                    </div>
                </div>
                <div class="categories__item">
                    <div class="categories__item__icon">
                        <span class="flaticon-005-pancake"></span>
                        <h5>Red Velvet</h5>
                    </div>
                </div>
                <div class="categories__item">
                    <div class="categories__item__icon">
                        <span class="flaticon-030-cupcake-2"></span>
                        <h5>Biscuit</h5>
                    </div>
                </div>
                <div class="categories__item">
                    <div class="categories__item__icon">
                        <span class="flaticon-006-macarons"></span>
                        <h5>Donut</h5>
                    </div>
                </div>
                <div class="categories__item">
                    <div class="categories__item__icon">
                        <span class="flaticon-006-macarons"></span>
                        <h5>Cupcake</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> {% endcomment %}
<!-- Categories Section End -->

<!-- Team Section Begin -->
<section class="team spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-7 col-md-7 col-sm-7">
                <div class="section-title">
                    <span>Our team</span>
                    <h2>Sweet Baker </h2>
                </div>
            </div>
        </div>
        <div class="row">
            {% for item in ourTeam %}
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="team__item set-bg" data-setbg="{{item.img.url}}">
                    <div class="team__item__text">
                        <h6>{{item.name}}</h6>
                        <span>{{item.desc}}</span>
                        <div class="team__item__social">
                            {% if item.fb %}
                            <a href="{{item.fb}}"><i class="fa fa-facebook"></i></a>
                            {% endif %}
                            {% if item.X %}
                            <a href="{{item.X}}"><i class="fa fa-twitter"></i></a>
                            {% endif %}
                            {% if item.ig %}
                            <a href="{{item.ig}}"><i class="fa fa-instagram"></i></a>                              
                            {% endif %}
                            {% if item.ytb %}
                            <a href="{{item.ytb}}"><i class="fa fa-youtube-play"></i></a>                              
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<!-- Team Section End -->
{% endblock content %}