home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home,name='home'),
]

login2/urls.py
from django.urls import path
from . import views


app_name = 'login2'
urlpatterns = [
    path('', views.login2,name='login2'),
 ]

myshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('',include('home.urls')),
    path('about/',include('about.urls')),
    path('register/', include('register.urls')),
    path('login/',include('login2.urls')),
    path('dangxuat/', include('logout2.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

register/urls.py
from django.urls import path
from . import views

app_name = 'register'
urlpatterns = [
    path('',views.register,name="register"),
]

login2/models.py
from django.db import models

# Create your models here.

login2/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login
from django.contrib import messages

# Create your views here.
def login2(request):
    errors = []
    next = request.GET.get("next")
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        is_auth = authenticate(username=username,password=password)
        if is_auth:
            login(request,is_auth)
            if next:
                return redirect(next)
            return redirect("home:home")
        else:
            error = "Tài khoản hoặc mật khẩu không đúng"
            errors.append(error)
            messages.warning(request,error)
    context = {
        "errors": errors
    }
    return render(request,"login2/login.html",context)

login2/templates/login2/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" href="{% static "login/css/style.css" %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" />
</head>
<body>
    <!-- Form without bootstrap -->
    <div class="auth-wrapper">
        <div class="auth-container">
            <div class="auth-action-left">
                <div class="auth-form-outer">
                    <h2 class="auth-form-title">
                        Sign In
                    </h2>
                    <form class="login-form" method="POST" action="">
                        {% csrf_token %}
                        <input name="username" class="auth-form-input" placeholder="Email">
                        <div class="input-icon">
                            <input type="password" class="auth-form-input" placeholder="Password" name="password">
                            <i class="fa fa-eye show-password"></i>
                        </div>
                        <div class="footer-action">
                            <input type="submit" value="Sign In" class="auth-submit">
                            <a href="{% url "register:register" %}" class="auth-btn-direct">Sign Up</a>
                        </div>
                    </form>
                    {% for erorr in errors %}
                         <p>{{erorr}}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="auth-action-right">
                <div class="auth-image">
                    <img src="{% static "login/assets/vector.jpg" %}" alt="login">
                </div>
            </div>
        </div>

    </div>
    <script src="{% static "login/js/common.js" %}"></script>
</body>
</html>