home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home,name='home'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('',include('home.urls')),
    path('about/',include('about.urls')),
    path('register/', include('register.urls')),
    path('login/',include('login2.urls')),
    path('dangxuat/', include('logout2.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views

app_name = 'product'
urlpatterns = [
    path('', views.products,name='list'),
    path('detail/<int:id>', views.detail, name='detail'),
]

product/models.py
from django.db import models
from category.models import CategoryModel
import os


# Create your models here.
class ProductModel(models.Model):
    product_name = models.CharField(max_length=100)
    summary = models.CharField(max_length=500,null = True)
    price = models.IntegerField(null=True)
    quantity = models.IntegerField(default=0)
    description = models.TextField(null=True)
    # sale = models.IntegerField(null=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    delete_flag = models.BooleanField(default=False)
    image = models.ImageField(null=True,upload_to="images/")
    category = models.ForeignKey(CategoryModel,on_delete=models.PROTECT, null=True)

    def __str__(self):
        return self.product_name
    

product/views.py
from django.shortcuts import render
from .models import ProductModel
from category.models import CategoryModel
from django.conf import settings
from django.db.models import Q
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage

# Create your views here.
def products(request):
    limit = settings.DEFAULT_LIMIT #3
    keyword = request.GET.get("keyword","")
    category1 = request.GET.get("category","")
    page = request.GET.get("page",1)
    sort = request.GET.get("sort")
    if keyword != ""and category1 !="":
        category2 = CategoryModel.objects.get(id=category1)
        product_list=ProductModel.objects.filter(
            Q(product_name__icontains=keyword)
            | Q(summary__icontains=keyword)
            | Q(description__icontains=keyword), category=category2
        )
    elif keyword == "" and category1 !="":
        category2 = CategoryModel.objects.get(id=category1)
        product_list=ProductModel.objects.filter( category=category2 )
    elif keyword != "" and category1 =="":
        product_list=ProductModel.objects.filter(
            Q(product_name__icontains=keyword)
            | Q(summary__icontains=keyword)
            | Q(description__icontains=keyword)
        )
        
    else:
        product_list = ProductModel.objects.all()
    if sort not in ["-create_at","create_at","product_name","price",'-price']:
        sort = settings.DEFAULT_SORT
    category = CategoryModel.objects.all()
    
    product_list = product_list.order_by(sort)
    product_list_paging = Paginator(product_list, limit)
    try:
        product_list_paging = product_list_paging.get_page(page)
    except PageNotAnInteger:
        product_list_paging = product_list_paging.get_page(1)
    except EmptyPage:
        product_list_paging = product_list_paging.get_page(product_list_paging.num_pages)
    context = {
        'products_list': product_list_paging,
        'category': category
    }
    return render(request,"product/list.html",context)


def detail(request,id):
    product = ProductModel.objects.get(id=id)
    context={
        "product": product,
    }
    return render(request,"product/detail.html",context)

product/templates/product/detail.html
{% extends "home/base.html" %}
{% block content %}
<section class="product-details spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="product__details__img">
                    <div class="product__details__big__img">
                        <img class="big_img" src="{{product.image.url}}" alt="">
                    </div>
                    {% comment %} <div class="product__details__thumb">
                        <div class="pt__item active">
                            <img data-imgbigurl="img/shop/details/product-big-2.jpg"
                            src="img/shop/details/product-big-2.jpg" alt="">
                        </div>
                        <div class="pt__item">
                            <img data-imgbigurl="img/shop/details/product-big-1.jpg"
                            src="img/shop/details/product-big-1.jpg" alt="">
                        </div>
                        <div class="pt__item">
                            <img data-imgbigurl="img/shop/details/product-big-4.jpg"
                            src="img/shop/details/product-big-4.jpg" alt="">
                        </div>
                        <div class="pt__item">
                            <img data-imgbigurl="img/shop/details/product-big-3.jpg"
                            src="img/shop/details/product-big-3.jpg" alt="">
                        </div>
                        <div class="pt__item">
                            <img data-imgbigurl="img/shop/details/product-big-5.jpg"
                            src="img/shop/details/product-big-5.jpg" alt="">
                        </div>
                    </div> {% endcomment %}
                </div>
            </div>
            <div class="col-lg-6">
                <div class="product__details__text">
                    <div class="product__label">{{product.category}}</div>
                    <h4>{{product.product_name}}</h4>
                    <h5>{{product.price}} VNĐ</h5>
                    <p>{{product.summary}}</p>
                    <div class="product__details__option">
                        <div class="quantity">
                            <div class="pro-qty">
                                <input type="text" value="2">
                            </div>
                        </div>
                        <a href="#" class="primary-btn">Add to cart</a>
                        <a href="#" class="heart__btn"><span class="icon_heart_alt"></span></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="product__details__tab">
            <div class="col-lg-12">
                <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" data-toggle="tab" href="#tabs-1" role="tab">Description</a>
                    </li>
                    {% comment %} <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#tabs-3" role="tab">Previews(1)</a>
                    </li> {% endcomment %}
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="tabs-1" role="tabpanel">
                        <div class="row d-flex justify-content-center">
                            <div class="col-lg-8">
                                <p>{{product.description}}</p>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane" id="tabs-2" role="tabpanel">
                        <div class="row d-flex justify-content-center">
                            <div class="col-lg-8">
                                <p>This delectable Strawberry Pie is an extraordinary treat filled with sweet and
                                    tasty chunks of delicious strawberries. Made with the freshest ingredients, one
                                    bite will send you to summertime. Each gift arrives in an elegant gift box and
                                    arrives with a greeting card of your choice that you can personalize online!2
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane" id="tabs-3" role="tabpanel">
                        <div class="row d-flex justify-content-center">
                            <div class="col-lg-8">
                                <p>This delectable Strawberry Pie is an extraordinary treat filled with sweet and
                                    tasty chunks of delicious strawberries. Made with the freshest ingredients, one
                                    bite will send you to summertime. Each gift arrives in an elegant gift box and
                                    arrives with a greeting card of your choice that you can personalize online!3
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Shop Details Section End -->

<!-- Related Products Section Begin -->
{% comment %} <section class="related-products spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="section-title">
                    <h2>Related Products</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="related__products__slider owl-carousel">
                <div class="col-lg-3">
                    <div class="product__item">
                        <div class="product__item__pic set-bg" data-setbg="img/shop/product-1.jpg">
                            <div class="product__label">
                                <span>Cupcake</span>
                            </div>
                        </div>
                        <div class="product__item__text">
                            <h6><a href="#">Dozen Cupcakes</a></h6>
                            <div class="product__item__price">$32.00</div>
                            <div class="cart_add">
                                <a href="#">Add to cart</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="product__item">
                        <div class="product__item__pic set-bg" data-setbg="img/shop/product-2.jpg">
                            <div class="product__label">
                                <span>Cupcake</span>
                            </div>
                        </div>
                        <div class="product__item__text">
                            <h6><a href="#">Cookies and Cream</a></h6>
                            <div class="product__item__price">$30.00</div>
                            <div class="cart_add">
                                <a href="#">Add to cart</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="product__item">
                        <div class="product__item__pic set-bg" data-setbg="img/shop/product-3.jpg">
                            <div class="product__label">
                                <span>Cupcake</span>
                            </div>
                        </div>
                        <div class="product__item__text">
                            <h6><a href="#">Gluten Free Mini Dozen</a></h6>
                            <div class="product__item__price">$31.00</div>
                            <div class="cart_add">
                                <a href="#">Add to cart</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="product__item">
                        <div class="product__item__pic set-bg" data-setbg="img/shop/product-4.jpg">
                            <div class="product__label">
                                <span>Cupcake</span>
                            </div>
                        </div>
                        <div class="product__item__text">
                            <h6><a href="#">Cookie Dough</a></h6>
                            <div class="product__item__price">$25.00</div>
                            <div class="cart_add">
                                <a href="#">Add to cart</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="product__item">
                        <div class="product__item__pic set-bg" data-setbg="img/shop/product-5.jpg">
                            <div class="product__label">
                                <span>Cupcake</span>
                            </div>
                        </div>
                        <div class="product__item__text">
                            <h6><a href="#">Vanilla Salted Caramel</a></h6>
                            <div class="product__item__price">$05.00</div>
                            <div class="cart_add">
                                <a href="#">Add to cart</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="product__item">
                        <div class="product__item__pic set-bg" data-setbg="img/shop/product-6.jpg">
                            <div class="product__label">
                                <span>Cupcake</span>
                            </div>
                        </div>
                        <div class="product__item__text">
                            <h6><a href="#">German Chocolate</a></h6>
                            <div class="product__item__price">$14.00</div>
                            <div class="cart_add">
                                <a href="#">Add to cart</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section> {% endcomment %}
{% endblock content %}

product/templates/product/list.html
{% extends "home/base.html" %}
{% block content %}
  <!-- Breadcrumb Begin -->
  <div class="breadcrumb-option">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6">
                <div class="breadcrumb__text">
                    <h2>Shop</h2>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6">
                <div class="breadcrumb__links">
                    <a href="{% url "home:home" %}">Home</a>
                    <span>Shop</span>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->

<!-- Shop Section Begin -->

<section class="shop spad">
    <div class="container">
        <div class="shop__option">
            <div class="row">
                <div class="col-lg-7 col-md-7">
                    <div class="shop__option__search">
                        <form action="">
                            <select name="category" id="mySelect" >
                                <option value="">Category</option>
                                {% for item in category %}
                                  <option value="{{item.id}}">{{item.category_name}}</option>
                                {% endfor %}                        
                            </select>
                            <input type="text" placeholder="Search" name="keyword">
                            <button type="submit"><i class="fa fa-search"></i></button>
                        </form>
                    </div>
                </div>
                <div class="col-lg-5 col-md-5">
                    <div class="dropdown shop__option__right">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" style="background-color:  white; color: black;">
                          Sắp xếp theo
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="?sort=-create_at{% for k,v in request.GET.items %}{% if k != 'sort' %}&{{k}}={{v}}{% endif %}{% endfor %}">Mới nhất</a>
                            <a class="dropdown-item" href="?sort=create_at{% for k,v in request.GET.items %}{% if k != 'sort' %}&{{k}}={{v}}{% endif %}{% endfor %}">Cũ nhất</a>
                            <a class="dropdown-item" href="?sort=product_name{% for k,v in request.GET.items %}{% if k != 'sort' %}&{{k}}={{v}}{% endif %}{% endfor %}">Tên sản phẩm</a>
                            <a class="dropdown-item" href="?sort=price{% for k,v in request.GET.items %}{% if k != 'sort' %}&{{k}}={{v}}{% endif %}{% endfor %}">Giá tăng</a>
                            <a class="dropdown-item" href="?sort=-price{% for k,v in request.GET.items %}{% if k != 'sort' %}&{{k}}={{v}}{% endif %}{% endfor %}">Giá giảm</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            {% for item in products_list %}
            {% if not item.delete_flag %}
            <a href="{% url "product:detail" item.id%}">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="product__item">
                        <div class="product__item__pic set-bg" data-setbg="{{item.image.url}}">
                            <div class="product__label">
                                <span>{{item.category}}</span>
                            </div>
                        </div>
                        <div class="product__item__text">
                            <h6><a href="#">{{item.product_name}}</a></h6>
                            <div class="product__item__price">{{item.price}} VNĐ</div>
                            <div class="cart_add">
                                <a href="#">Add to cart </a>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
            {% endif %}
            {% endfor %}
        </div>
        <div class="shop__last__option">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <ul class="pagination">
                        <li class="page-item {% if not products_list.has_previous %} disabled {% endif %}">
                          <a class="page-link" href="?page={% if products_list.has_previous %}{{products_list.previous_page_number}}{% for k,v in request.GET.items %}{% if k != 'page' %}&{{k}}={{v}}{% endif %}{% endfor %}{% endif %}">Previous</a>
                        </li>
                        <li class="page-item active" aria-current="page">
                          <a class="page-link" href="#">{{products_list.number}} / {{products_list.paginator.num_pages}}</a>
                        </li>
                        <li class="page-item {% if not products_list.has_next %} disabled {% endif %}" >
                          <a class="page-link" href="?page={% if products_list.has_next %}{{products_list.next_page_number}}{% endif %}{% for k,v in request.GET.items %}{% if k != 'page' %}&{{k}}={{v}}{% endif %}{% endfor %}">Next</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Shop Section End -->
{% endblock content %}